export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000';

export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  BUILDINGS: '/buildings',
  BUILDING_DETAILS: (id: string) => `/buildings/${id}`,
  UNITS: '/units',
  TENANTS: '/tenants',
  TENANT_DETAILS: (id: string) => `/tenants/${id}`,
  LEASES: '/leases',
  LEASE_DETAILS: (id: string) => `/leases/${id}`,
  CREATE_LEASE: '/leases/new',
  METERS: '/meters',
  MAIN_METERS: '/main-meters',
  SENSORS: '/sensors',
  PROTOCOLS: '/protocols',
  MOVE_IN_PROTOCOLS: '/protocols/move-in',
  MOVE_OUT_PROTOCOLS: '/protocols/move-out',
  MESSAGES: '/messages',
  TASKS: '/tasks',
  WLAN: '/wlan',
  CONSUMPTION: '/consumption',
  BILLING: '/billing',
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/v1/mandator/auth/login',
    LOGOUT: '/api/v1/mandator/auth/logout',
    REFRESH: '/api/v1/mandator/auth/refresh',
    FORGOT_PASSWORD: '/api/v1/mandator/auth/forgot-password',
    RESET_PASSWORD: '/api/v1/mandator/auth/reset-password',
  },
  BUILDINGS: {
    LIST: '/api/v1/mandator/buildings',
    CREATE: '/api/v1/mandator/buildings',
    GET: (id: string) => `/api/v1/mandator/buildings/${id}`,
    UPDATE: (id: string) => `/api/v1/mandator/buildings/${id}`,
    DELETE: (id: string) => `/api/v1/mandator/buildings/${id}`,
  },
  UNITS: {
    LIST: '/api/v1/mandator/units',
    CREATE: '/api/v1/mandator/units',
    GET: (id: string) => `/api/v1/mandator/units/${id}`,
    UPDATE: (id: string) => `/api/v1/mandator/units/${id}`,
    DELETE: (id: string) => `/api/v1/mandator/units/${id}`,
  },
  TENANTS: {
    LIST: '/api/v1/mandator/tenants',
    CREATE: '/api/v1/mandator/tenants',
    GET: (id: string) => `/api/v1/mandator/tenants/${id}`,
    UPDATE: (id: string) => `/api/v1/mandator/tenants/${id}`,
    DELETE: (id: string) => `/api/v1/mandator/tenants/${id}`,
  },
  LEASES: {
    LIST: '/api/v1/mandator/leases',
    GENERATE_PDF: '/api/v1/mandator/leases/generate-pdf',
    CREATE: '/api/v1/mandator/leases',
    GET: (id: string) => `/api/v1/mandator/leases/${id}`,
    UPDATE: (id: string) => `/api/v1/mandator/leases/${id}`,
    TERMINATE: (id: string) => `/api/v1/mandator/leases/${id}/terminate`,
    DELETE: (id: string) => `/api/v1/mandator/leases/${id}`,
  },
  METERS: {
    LIST: '/api/v1/mandator/meters',
    CREATE: '/api/v1/mandator/meters',
    GET: (id: string) => `/api/v1/mandator/meters/${id}`,
    UPDATE: (id: string) => `/api/v1/mandator/meters/${id}`,
    DELETE: (id: string) => `/api/v1/mandator/meters/${id}`,
  },
  MAIN_METERS: {
    LIST: '/api/v1/mandator/main-meters',
    CREATE: '/api/v1/mandator/main-meters',
    GET: (id: string) => `/api/v1/mandator/main-meters/${id}`,
    ADD_READING: (id: string) => `/api/v1/mandator/main-meters/${id}/readings`,
    GET_READINGS: (id: string) => `/api/v1/mandator/main-meters/${id}/readings`,
    PLAUSIBILITY_CHECK: (id: string) => `/api/v1/mandator/main-meters/${id}/plausibility-check`,
  },
  SENSORS: {
    LIST: '/api/v1/mandator/sensors',
    CREATE: '/api/v1/mandator/sensors',
    GET: (id: string) => `/api/v1/mandator/sensors/${id}`,
    UPDATE: (id: string) => `/api/v1/mandator/sensors/${id}`,
    ACTIVATE: (id: string) => `/api/v1/mandator/sensors/${id}/activate`,
    DEACTIVATE: (id: string) => `/api/v1/mandator/sensors/${id}/deactivate`,
    DELETE: (id: string) => `/api/v1/mandator/sensors/${id}`,
  },
  MOVE_IN_PROTOCOLS: {
    LIST: '/api/v1/mandator/move-in-protocols',
    CREATE: '/api/v1/mandator/move-in-protocols',
    GET: (id: string) => `/api/v1/mandator/move-in-protocols/${id}`,
    UPDATE: (id: string) => `/api/v1/mandator/move-in-protocols/${id}`,
    SIGN: (id: string) => `/api/v1/mandator/move-in-protocols/${id}/sign`,
    GENERATE_PDF: (id: string) => `/api/v1/mandator/move-in-protocols/${id}/pdf`,
    DELETE: (id: string) => `/api/v1/mandator/move-in-protocols/${id}`,
  },
  MOVE_OUT_PROTOCOLS: {
    LIST: '/api/v1/mandator/move-out-protocols',
    CREATE: '/api/v1/mandator/move-out-protocols',
    GET: (id: string) => `/api/v1/mandator/move-out-protocols/${id}`,
    UPDATE: (id: string) => `/api/v1/mandator/move-out-protocols/${id}`,
    SIGN: (id: string) => `/api/v1/mandator/move-out-protocols/${id}/sign`,
    GENERATE_PDF: (id: string) => `/api/v1/mandator/move-out-protocols/${id}/pdf`,
  },
  MESSAGES: {
    LIST: '/api/v1/mandator/messages',
    SEND: '/api/v1/mandator/messages',
  },
  TASKS: {
    LIST: '/api/v1/mandator/tasks',
    CREATE: '/api/v1/mandator/tasks',
  },
  WLAN: {
    LIST: '/api/v1/mandator/wlan',
    CREATE: '/api/v1/mandator/wlan',
    GET: (id: string) => `/api/v1/mandator/wlan/${id}`,
    REGENERATE: (id: string) => `/api/v1/mandator/wlan/${id}/regenerate`,
    DEACTIVATE: (id: string) => `/api/v1/mandator/wlan/${id}/deactivate`,
  },
  CONSUMPTION: {
    OVERVIEW: '/api/v1/mandator/consumption/overview',
    BY_UNIT: (unitId: string) => `/api/v1/mandator/consumption/unit/${unitId}`,
    BY_TENANT: (tenantId: string) => `/api/v1/mandator/consumption/tenant/${tenantId}`,
  },
  BILLING: {
    LIST: '/api/v1/mandator/billing',
    CREATE: '/api/v1/mandator/billing',
    GET: (id: string) => `/api/v1/mandator/billing/${id}`,
    GENERATE_PDF: (id: string) => `/api/v1/mandator/billing/${id}/pdf`,
  },
} as const;
